import spotipy
from spotipy.oauth2 import SpotifyOAuth
import time
import os
import difflib

SCOPE = "user-modify-playback-state user-read-playback-state playlist-read-private playlist-read-collaborative user-library-read user-library-modify user-top-read"

def init_spotify():
    """Initializes and verifies Spotify permissions."""
    print("Verifying Spotify permissions...")
    try:
        sp_auth = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=SCOPE))
        sp_auth.me() # Force an API call to ensure the token is cached and valid
        print("Spotify permissions verified!")
        return True
    except Exception as e:
        print(f"Spotify Auth Error: {e}\nPlease check your .env file or authorize in the browser.")
        return False

def _get_active_device(sp):
    """Helper to find an active Spotify device."""
    devices = sp.devices()
    if not devices.get('devices'):
        os.system("start spotify:")
        time.sleep(1)
        devices = sp.devices()
        if not devices.get('devices'):
            return None
            
    for d in devices['devices']:
        if d['is_active']:
            return d['id']
    return devices['devices'][0]['id'] if devices['devices'] else None

def play_spotify_music(query: str, search_type: str = "track", force_play: bool = False) -> str:
    """Searches Spotify for a track or playlist and plays it."""
    try:
        sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=SCOPE))
        device_id = _get_active_device(sp)
        if not device_id:
            return "Could not find an active Spotify device. Please open Spotify manually first."

        if search_type == "playlist":
            query_lower = query.lower()
            
            # Special case for "Liked Songs"
            if "liked songs" in query_lower or "my liked" in query_lower:
                user_id = sp.me()['id']
                sp.start_playback(device_id=device_id, context_uri=f"spotify:user:{user_id}:collection")
                return "Successfully started playing your Liked Songs."

            # Check personal playlists first
            user_playlists = sp.current_user_playlists()
            personal_match = None
            while user_playlists:
                for pl in user_playlists['items']:
                    if query_lower in pl['name'].lower() or pl['name'].lower() in query_lower:
                        personal_match = pl
                        break
                if personal_match or not user_playlists['next']:
                    break
                user_playlists = sp.next(user_playlists)
                
            if personal_match:
                sp.start_playback(device_id=device_id, context_uri=personal_match['uri'])
                return f"Successfully started playing your personal playlist: {personal_match['name']}."

            # Special case for Spotify-generated playlists
            if "discover weekly" in query_lower or "release radar" in query_lower or "daylist" in query_lower:
                return f"I couldn't find '{query}' in your library. Since it's a playlist generated by Spotify, you must first click 'Save to Library' (the heart icon) on it in your Spotify app before I can access it."

            # Fallback to global public search
            results = sp.search(q=query, type='playlist', limit=1)
            if results['playlists']['items']:
                playlist_uri = results['playlists']['items'][0]['uri']
                playlist_name = results['playlists']['items'][0]['name']
                sp.start_playback(device_id=device_id, context_uri=playlist_uri)
                return f"Successfully started playing the public playlist: {playlist_name}."
            else:
                return f"Could not find any playlist matching '{query}'."
        elif search_type == "artist":
            results = sp.search(q=query, type='artist', limit=1)
            if results['artists']['items']:
                artist_uri = results['artists']['items'][0]['uri']
                artist_name = results['artists']['items'][0]['name']
                sp.start_playback(device_id=device_id, context_uri=artist_uri)
                return f"Successfully started playing songs by {artist_name}."
            else:
                return f"Could not find any artist matching '{query}'."
        else:
            results = sp.search(q=query, type='track', limit=1)
            if results['tracks']['items']:
                track_uri = results['tracks']['items'][0]['uri']
                track_name = results['tracks']['items'][0]['name']
                artist_name = results['tracks']['items'][0]['artists'][0]['name']
                
                match_str = f"{track_name} {artist_name}".lower()
                similarity = difflib.SequenceMatcher(None, query.lower(), match_str).ratio()
                
                if not force_play and similarity < 0.8:
                    return f"Found '{track_name}' by '{artist_name}'. This might be a mismatch for '{query}'. Ask the user if this is the song they meant. If they say yes, call this tool again with force_play=true."
                
                sp.start_playback(device_id=device_id, uris=[track_uri])
                return f"Successfully started playing {track_name} by {artist_name}."
            else:
                return f"Could not find any song matching '{query}'."
    except Exception as e:
        return f"Spotify API Error: {str(e)}"

def list_my_playlists() -> str:
    """Lists the names of the user's personal Spotify playlists."""
    try:
        sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=SCOPE))
        playlists = sp.current_user_playlists(limit=15)
        
        if not playlists or not playlists['items']:
            return "You don't have any personal playlists saved."
            
        names = [pl['name'] for pl in playlists['items']]
        return "Your playlists: " + ", ".join(names)
    except Exception as e:
        return f"Spotify API Error: {str(e)}"

def what_is_playing() -> str:
    """Gets the currently playing song."""
    try:
        sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=SCOPE))
        current = sp.current_playback()
        if current and current.get('is_playing') and current.get('item'):
            track_name = current['item']['name']
            artist_name = current['item']['artists'][0]['name']
            return f"You are currently listening to '{track_name}' by {artist_name}."
        return "Nothing is currently playing on Spotify."
    except Exception as e:
        return f"Spotify API Error: {str(e)}"

def like_current_song() -> str:
    """Adds the currently playing song to the user's Liked Songs."""
    try:
        sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=SCOPE))
        current = sp.current_playback()
        if current and current.get('item'):
            track_id = current['item']['id']
            track_name = current['item']['name']
            sp.current_user_saved_tracks_add(tracks=[track_id])
            return f"Successfully added '{track_name}' to your Liked Songs."
        return "Nothing is currently playing to add."
    except Exception as e:
        return f"Spotify API Error: {str(e)}"

# ==========================================
# SCHEMAS
# ==========================================

play_spotify_schema = {
    "type": "function",
    "function": {
        "name": "play_spotify_music",
        "description": "Searches Spotify and plays a specific song, playlist, or artist. ONLY use this when the user names a specific song, playlist, or artist to play.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string", 
                    "description": "The exact search engine query."
                },
                "search_type": {
                    "type": "string",
                    "enum": ["track", "playlist", "artist"],
                    "description": "Whether to search for a track, playlist, or artist."
                },
                "force_play": {
                    "type": "boolean",
                    "description": "Set to true ONLY if confirming a fuzzy match."
                }
            },
            "required": ["query", "search_type"]
        }
    }
}

list_playlists_schema = {
    "type": "function",
    "function": {
        "name": "list_my_playlists",
        "description": "Lists the names of the user's personal Spotify playlists.",
        "parameters": {
            "type": "object",
            "properties": {},
            "required": []
        }
    }
}

what_is_playing_schema = {
    "type": "function",
    "function": {
        "name": "what_is_playing",
        "description": "Tells the user what song is currently playing on Spotify.",
        "parameters": {
            "type": "object",
            "properties": {},
            "required": []
        }
    }
}

like_song_schema = {
    "type": "function",
    "function": {
        "name": "like_current_song",
        "description": "Adds the currently playing song to the user's Liked Songs (Favorites). Use when user asks to 'like this', 'add to favorites', 'save this song', etc.",
        "parameters": {
            "type": "object",
            "properties": {},
            "required": []
        }
    }
}
